### PR TITLE
support php 8.4

### PR DESCRIPTION
**Pull request by fideloper**

### CODE REVIEW

**Comment by KTanAug21** [comment]
Looks great, thank you @fideloper for adding this Pull Request to include PHP 8.4 compatibility!

@rubys can you please check if this can be merged( thank you in advance! )?
Here is how it basically goes:
[flyctl checks ](https://github.com/superfly/flyctl/blob/13b5ec32fe769dadd362e0e29bece1904f391088/scanner/laravel.go#L63)php version from composer.json or the php -v command
1. [flyctl calls ](https://github.com/superfly/flyctl/blob/13b5ec32fe769dadd362e0e29bece1904f391088/scanner/laravel.go#L81)the dockerfile-laravel and passes the PHP version

2. dockerfile-laravel generates the same Dockerfile and [required files ](https://github.com/fly-apps/dockerfile-laravel/pull/45/files#diff-fe405c70bcb7be8540ca3d17c2f8da250d5e041989309b517f3da3dbc8983da0R145)needed based on scan

3. The dockerfile generated uses the PHP version identified by flyctl, and uses it to[ use the proper php config file](https://github.com/fly-apps/dockerfile-laravel/blob/main/resources/views/dockerfile.blade.php#L32)!

**Comment by rubys** [comment]
What are the steps for making a release?

**Comment by fideloper** [comment]
I believe they are 
1. make/push a tag
2. make a release from github’s release page within the repo

I use their magic AI button that creates the release notes.

**Comment by rubys** [comment]
Oh, so unlike Ruby and Node and others that have a separate repository, composer can use github as it's repository.  TIL.  Sweet!

**Pull request merged**
